### ISSUE TITLE
Make it english

### ISSUE THREAD

**Issue by coolkidsrule101** [TheNewHEROBRINEX/Murder#13]
i cant read the phar on poggit you should look at it because not in english

**Comment by TheNewHEROBRINEX** [comment]
1. 1.2 is not supported
2. You can compile it yourself using DevTools

**Comment by coolkidsrule101** [comment]
ok
/

**Comment by coolkidsrule101** [comment]
but it does work in 1.2 but the lang is differnt

**Comment by TheNewHEROBRINEX** [comment]
It can't work in 1.2. I didn't test but I'm sure and you have to switch to the english branch before downloading the ZIP
