### ISSUE TITLE
is this plugin fully functional with pocketmine alpha 10 with no bugs?

### ISSUE THREAD

**Issue by CyanCreeper** [TheNewHEROBRINEX/Murder#16]

**Comment by TheNewHEROBRINEX** [comment]
I think there are no bugs but if you find one please let me know

**Comment by CyanCreeperPlayz** [comment]
I have added the plugin to the server but, when I do /pl it is highlighted red and its not working.

**Comment by TheNewHEROBRINEX** [comment]
@CyanCreeperPlayz read the error. It says that you have to change the name of the world you want to use as hub in the config.yml

**Comment by CyanCreeper** [comment]
To confirm for any of you out there this plugin has no bugs. 🙂
