### ISSUE TITLE
ERROR IN CONSOLE

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [TheNewHEROBRINEX/Murder#18]
MP.phar(9): include(string phar:///jar/pocketmine/pmmp/1.2.7-alpha10/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
25.12 11:29:07 [Server] Server thread/DEBUG #18 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
25.12 11:29:07 [Server] Server thread/DEBUG #17 src/pocketmine/Server(1737): pocketmine\Server->start()
25.12 11:29:07 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2149): pocketmine\Server->tickProcessor()
25.12 11:29:07 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2274): pocketmine\Server->tick()
25.12 11:29:07 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2522): pocketmine\network\Network->processInterfaces()
25.12 11:29:07 [Server] Server thread/DEBUG #13 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
25.12 11:29:07 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(82): raklib\server\ServerHandler->handlePacket()
25.12 11:29:07 [Server] Server thread/DEBUG #11 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 71.196.120.10:63828, raklib\protocol\EncapsulatedPacket object, integer 0)
25.12 11:29:07 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
25.12 11:29:07 [Server] Server thread/DEBUG #9 src/pocketmine/Player(2982): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
25.12 11:29:07 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
25.12 11:29:07 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
25.12 11:29:07 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
25.12 11:29:07 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
25.12 11:29:07 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(220): pocketmine\Player->chat(string /murder setarena 10 1)
25.12 11:29:07 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2121): pocketmine\Server->dispatchCommand(pocketmine\Player object, string murder setarena 10 1)
25.12 11:29:07 [Server] Server thread/DEBUG #2 src/pocketmine/Server(1982): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string murder setarena 10 1)
25.12 11:29:07 [Server] Server thread/DEBUG #1 src/pocketmine/command/SimpleCommandMap(258): TheNewHEROBRINE\Murder\MurderCommand->execute(pocketmine\Player object, string murder, array Array())
25.12 11:29:07 [Server] Server thread/DEBUG #0 Murder_v0.9 (2).phar/src/TheNewHEROBRINE/Murder/MurderCommand(99): TheNewHEROBRINE\Murder\MurderMain->getArenasCfg()
25.12 11:29:07 [Server] Server thread/CRITICAL TypeError: "Return value of TheNewHEROBRINE\Murder\MurderMain::getArenasCfg() must be an instance of pocketmine\utils\Config, null returned" (EXCEPTION) in "Murder_v0.9 (2).phar/src/TheNewHEROBRINE/Murder/MurderMain" at line 171
25.12 11:29:07 [Server] Server thread/CRITICAL Unhandled exception executing command 'murder setarena 10 1' in murder: Return value of TheNewHEROBRINE\Murder\MurderMain::getArenasCfg() must be an instance of pocketmine\utils\Config, null returned

**Comment by TheNewHEROBRINEX** [comment]
Is the plugin enabled? (Green name in /plugins)

**Comment by CyanCreeperPlayz** [comment]
Omg it is working that you so much!

**Comment by CyanCreeperPlayz** [comment]
But, can you translate the plugin into english for me?
