### ISSUE TITLE
Can you please make the plugin in English?

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [TheNewHEROBRINEX/Murder#19]
I’ve just installed the plugin onto the server. Set the world in the config file, etc. Can I just say this is one of the best MCPE plugin. It really is. Sound effects amazing! Just everything about it is awesome. Makes it feel like the MCPC MURDER MYSTERY. 

Anyway, aside from that would you mind translating this plugin to ENGLISH and seeing it to my email cyancreeper31@gmail.com or upload it here. Thank you so much!

**Comment by CyanCreeper** [comment]
Please make the plugin English.

**Comment by TheNewHEROBRINEX** [comment]
A translation system will be implemented soon but for now you can use this unofficial English version https://github.com/FienixEC/Murder/tree/1.2-WIP

**Comment by CyanCreeperPlayz** [comment]
Is it the same plugin?

**Comment by TheNewHEROBRINEX** [comment]
Yes but be sure to download the 1.2-WIP branch

**Comment by CyanCreeperPlayz** [comment]
Thank you so much. Your plugins are amazing! Do you have any others that are working? Eggwars? Bedwars? Please.

**Comment by TheNewHEROBRINEX** [comment]
At the moment no sorry
