### ISSUE TITLE
Would you mind updating a plugin for me? It's call SexyMOTD. 

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [TheNewHEROBRINEX/Murder#21]
Please email me cyancreeper31@gmail.com

**Comment by TheNewHEROBRINEX** [comment]
I'm only available on Telegram @TheNewHEROBRINEX

**Comment by CyanCreeperPlayz** [comment]
ok sure can i upload it here?

**Comment by CyanCreeperPlayz** [comment]
we just got the sexy motd plugin updated...and we are looking for an NPC PLUGIN

**Comment by TheNewHEROBRINEX** [comment]
Slapper?

**Comment by CyanCreeperPlayz** [comment]
The slappers plugin is buggy...when we attempt to add a command...it says the command has been added but when we click it nothing happens

**Comment by CyanCreeperPlayz** [comment]
Yes, slapper. But, when we add a command to the slapper and when we go to click it nothing happens

**Comment by TheNewHEROBRINEX** [comment]
What command do you add?

**Comment by CyanCreeperPlayz** [comment]
/kits so that it could open the KITS UI

**Comment by TheNewHEROBRINEX** [comment]
You need to do /rca {player} kits because if you type only /kits it is executed by the console

**Comment by CyanCreeperPlayz** [comment]
ok let me try

**Comment by CyanCreeperPlayz** [comment]
OMG IT WORKED! THANK YOU SO MUCH!
