### ISSUE TITLE
UNKNOWN ERROR *PLEASE FIX*

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [TheNewHEROBRINEX/Murder#23]
9.12 09:12:05 [Server] Server thread/DEBUG #19 /jar/pocketmine/pmmp/1.2.7-alpha10/PocketMine-MP.phar(9): include(string phar:///jar/pocketmine/pmmp/1.2.7-alpha10/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
29.12 09:12:05 [Server] Server thread/DEBUG #18 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
29.12 09:12:05 [Server] Server thread/DEBUG #17 src/pocketmine/Server(1737): pocketmine\Server->start()
29.12 09:12:05 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2149): pocketmine\Server->tickProcessor()
29.12 09:12:05 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2274): pocketmine\Server->tick()
29.12 09:12:05 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2522): pocketmine\network\Network->processInterfaces()
29.12 09:12:05 [Server] Server thread/DEBUG #13 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
29.12 09:12:05 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(82): raklib\server\ServerHandler->handlePacket()
29.12 09:12:05 [Server] Server thread/DEBUG #11 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 71.196.120.10:61870, raklib\protocol\EncapsulatedPacket object, integer 0)
29.12 09:12:05 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
29.12 09:12:05 [Server] Server thread/DEBUG #9 src/pocketmine/Player(2982): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
29.12 09:12:05 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
29.12 09:12:05 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
29.12 09:12:05 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
29.12 09:12:05 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
29.12 09:12:05 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(220): pocketmine\Player->chat(string /murder setarena 10 20)
29.12 09:12:05 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2121): pocketmine\Server->dispatchCommand(pocketmine\Player object, string murder setarena 10 20)
29.12 09:12:05 [Server] Server thread/DEBUG #2 src/pocketmine/Server(1982): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string murder setarena 10 20)
29.12 09:12:05 [Server] Server thread/DEBUG #1 src/pocketmine/command/SimpleCommandMap(258): TheNewHEROBRINE\Murder\MurderCommand->execute(pocketmine\Player object, string murder, array Array())
29.12 09:12:05 [Server] Server thread/DEBUG #0 Murder_v0.9 (3).phar/src/TheNewHEROBRINE/Murder/MurderCommand(99): TheNewHEROBRINE\Murder\MurderMain->getArenasCfg()
29.12 09:12:05 [Server] Server thread/CRITICAL TypeError: "Return value of TheNewHEROBRINE\Murder\MurderMain::getArenasCfg() must be an instance of pocketmine\utils\Config, null returned" (EXCEPTION) in "Murder_v0.9 (3).phar/src/TheNewHEROBRINE/Murder/MurderMain" at line 171
29.12 09:12:05 [Server] Server thread/CRITICAL Unhandled exception executing command 'murder setarena 10 20' in murder: Return value of TheNewHEROBRINE\Murder\MurderMain::getArenasCfg() must be an instance of pocketmine\utils\Config, null returned

**Comment by TheNewHEROBRINEX** [comment]
Is the plugin green in /plugins?

**Comment by CyanCreeper** [comment]
Yes
