### ISSUE TITLE
Keep spawning.

### ISSUE THREAD

**Issue by treehousemc1** [TheNewHEROBRINEX/Murder#28]
I killed murder but still no win.

**Comment by TheNewHEROBRINEX** [comment]
Is there any error on the console?

**Comment by treehousemc1** [comment]
No i guess. I didnt check. Ill check later

**Comment by treehousemc1** [comment]
And also sometimes murder plugin will spawn slapper (cant remove)

**Comment by TheNewHEROBRINEX** [comment]
That may happen if the server restarts during a game but they will disappear when you finish next game

**Comment by treehousemc1** [comment]
Do you have twitter? if so add me @treehousemc    Lets talk at twitter about plugin issues

**Comment by TheNewHEROBRINEX** [comment]
If you still have this issue open another issue.
