### ISSUE TITLE
Japanese Language

### ISSUE THREAD

**Issue by PawarenessC** [TheNewHEROBRINEX/Murder#31]
I could not send a PR with a bug.
Sorry.

**Comment by TheNewHEROBRINEX** [comment]
Can't you translate the plugin to Japanese and submit a PR?

**Comment by Xxawareness** [comment]
I can not send a PR with a bug.
I'm sorry.

URL↓
https://www.dropbox.com/s/f6xkkmjeo57fz3o/jpn.ini

**Comment by Xxawareness** [comment]
Sorry.

**Comment by TheNewHEROBRINEX** [comment]
Oh ok thank you

**Comment by TheNewHEROBRINEX** [comment]
It's incomplete

**Comment by PawarenessC** [comment]
I'm sorry.
I will do PullRequest someday...
