### ISSUE TITLE
Name arena

### ISSUE THREAD

**Issue by dzangar** [TheNewHEROBRINEX/Murder#34]
How to find out the name of the arena?﻿

**Comment by TheNewHEROBRINEX** [comment]
It's the name of the folder of the world

**Comment by dzangar** [comment]
Video is more in detail?
I just do not know how to set everything up.

**Comment by TheNewHEROBRINEX** [comment]
I remember you that this plugin is for API version 3.0.0-ALPHA10 so I think it won't work on your pmmp installation anyway.

**Comment by dzangar** [comment]
I have 3.0.0-ALPHA10. Now how to configure I do not know.

**Comment by TheNewHEROBRINEX** [comment]
Did you read the README file? What did not you understand?

**Comment by dzangar** [comment]
I've read README
I just write to you with an interpreter. And I translate your language. I did not understand how to do this because of this! Can you help ?!

**Comment by TheNewHEROBRINEX** [comment]
You can set Russian as language for the plugin in config.yml

**Comment by dzangar** [comment]
I did not fully understand. If there was a video, then I probably could understand

**Comment by dzangar** [comment]
When will you do it?

**Comment by TheNewHEROBRINEX** [comment]
Do you still need help setting the plugin?

**Comment by TheNewHEROBRINEX** [comment]
I'm adding creating a video to show how to set up the plugin to the TODO list in #1.
