### ISSUE TITLE
Is this plugin abandoned?

### ISSUE THREAD

**Issue by GooglePlugin** [TheNewHEROBRINEX/Murder#36]
I noticed it hasn't been updated for about 10 months.

**Comment by TheNewHEROBRINEX** [comment]
I may consider updating this plugin someday.

**Comment by GooglePlugin** [comment]
Okay, I am looking forward to it.

**Comment by TheNewHEROBRINEX** [comment]
I have updated the plugin to be compatible with PocketMine-MP 3.0.0
