### ISSUE TITLE
Chat and Skins bug

### ISSUE THREAD

**Issue by LegoFan48737** [TheNewHEROBRINEX/Murder#39]
Ok, theres several issues I've found.
1st: There were 3 players, Me (VesperSoup48737), XxFairyLightsxX and xCLOUTboi. When the match started, our skins switched and i had Fairys skin, Clout had mine, and Fairy had Clouts skin. Not sure if this is intentional, as a way to disguise the murderer, or if its a bug.

2a: We were able to chat during the game, and
2b: in chat, our usernames got mixed up. I had Fairys, Clout had mine, and Fairy had Clouts username, and the same went for our Nametags. An easy fix for this issue would to just disable chat during the game, and set all nametags to blank.

Other than this, it works perfectly, and I love it!

**Comment by TheNewHEROBRINEX** [comment]
This minigame is based on the one of the Java Edition server play.mcpz.net. There, when the game begins, you get a random skin and a random name but since I have no skins to provide I decided to scramble the names and skins of the players who play the game instead.
