### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by oGalatico** [TheNewHEROBRINEX/Murder#4]
![screenshot_20170808-123454](https://user-images.githubusercontent.com/18704329/29080430-1efaa58c-7c36-11e7-86a2-95847227ef8d.png)

**Comment by TheNewHEROBRINEX** [comment]
The plugin is compatible with PocketMine-MP API 3.0.0-ALPHA7 so update your server to the latest version

**Comment by oGalatico** [comment]
:(
