### ISSUE TITLE
Sword

### ISSUE THREAD

**Issue by Matze997** [TheNewHEROBRINEX/Murder#42]
Really good Job but sometimes the Murder doesn't get his sword at the beginning

**Comment by TheNewHEROBRINEX** [comment]
Do you use PerWorldInventory?

**Comment by Matze997** [comment]
No

TheNewHEROBRINEX <notifications@github.com> schrieb am Sa., 29. Juni 2019,
14:20:

**Comment by Matze997** [comment]
But i think i've found the Error. It was because the Hotbar Plugin which
clear the inventory on World changing

TheNewHEROBRINEX <notifications@github.com> schrieb am Sa., 29. Juni 2019,
14:20:

**Comment by TheNewHEROBRINEX** [comment]
Is that plugin public? If yes can you link it here?

**Comment by Matze997** [comment]
it's on poggit an has the name Hotbar

TheNewHEROBRINEX <notifications@github.com> schrieb am Sa., 29. Juni 2019,
16:21:

**Comment by TheNewHEROBRINEX** [comment]
The only solution I can think of is to raise the priority of the EntityLevelChangeEvent event handler in my plugin but I don't think it's worth for only one plugin.

**Comment by Matze997** [comment]
I will Code my own Hotbar so the Problem will not apear

TheNewHEROBRINEX <notifications@github.com> schrieb am So., 30. Juni 2019,
17:51:

**Comment by TheNewHEROBRINEX** [comment]
Ok, thank you
