### ISSUE TITLE
Server Crash (PlayerDeathEvent)

### ISSUE THREAD

**Issue by funnycars** [TheNewHEROBRINEX/Murder#43]
It will be an error to defeat the player of the 128x128 HD skin

Error: StringTag cannot hold more than 32767 bytes, got string of length 65536

**Comment by derrenrafa** [comment]
Beacus we don't axport the 128×128 hd skin. And now we fix it

**Comment by TheNewHEROBRINEX** [comment]
To fix this issue the plugin should use the proper skin API provided by PocketMine-MP
