### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by vasilishunter** [TheNewHEROBRINEX/Murder#48]
Every time a player dies the server crashes

**Comment by TheNewHEROBRINEX** [comment]
Can you send the error please?

**Comment by vasilishunter** [comment]
TypeError: "Argument 2 passed to pocketmine\nbt\tag\StringTag::__construct() must be of the type string, object given, called in E:\UserFiles\VASILISH\GameServers\TC73018520816563733706432\plugins\Murder-master\src\TheNewHEROBRINE\Murder\MurderListener.php on line 194" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/StringTag" at line 41

**Comment by TheNewHEROBRINEX** [comment]
Can you send me also the backtrace (the lines in light grey that appear after the error)?

**Comment by vasilishunter** [comment]
PocketMine-MP Crash Dump Sat Nov 9 13:45:52 GMT 2019

Error: Argument 2 passed to pocketmine\nbt\tag\StringTag::__construct() must be of the type string, object given, called in E:\UserFiles\VASILISH\GameServers\TC73018520816563733706432\plugins\Murder-master\src\TheNewHEROBRINE\Murder\MurderListener.php on line 194
File: vendor/pocketmine/nbt/src/tag/StringTag
Line: 41
Type: TypeError

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Murder v0.9

Code:
[32]
[33] class StringTag extends NamedTag{
[34] /** @var string */
[35] private $value;
[36]
[37] /**
[38] * @param string $name
[39] * @param string $value
[40] */
[41] public function __construct(string $name = "", string $value = ""){
[42] parent::__construct($name);
[43] if(strlen($value) > 32767){
[44] throw new \InvalidArgumentException("StringTag cannot hold more than 32767 bytes, got string of length " . strlen($value));
[45] }
[46] $this->value = $value;
[47] }
[48]
[49] public function getType() : int{
[50] return NBT::TAG_String;
[51] }

Backtrace:
#0 plugins/Murder-master/src/TheNewHEROBRINE/Murder/MurderListener(194): pocketmine\nbt\tag\StringTag->__construct(string[4] Data, object pocketmine\utils\SerializedImage)
#1 src/pocketmine/plugin/MethodEventExecutor(38): TheNewHEROBRINE\Murder\MurderListener->onDeath(object pocketmine\event\player\PlayerDeathEvent)
#2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(object TheNewHEROBRINE\Murder\MurderListener, object pocketmine\event\player\PlayerDeathEvent)
#3 src/pocketmine/event/Event(97): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerDeathEvent)
#4 src/pocketmine/Player(3716): pocketmine\event\Event->call()
#5 src/pocketmine/entity/Living(639): pocketmine\Player->onDeath()
#6 src/pocketmine/Player(3705): pocketmine\entity\Living->kill()
#7 src/pocketmine/entity/Entity(1054): pocketmine\Player->kill()
#8 src/pocketmine/entity/Living(143): pocketmine\entity\Entity->setHealth(double 0)
#9 plugins/Murder-master/src/TheNewHEROBRINE/Murder/MurderListener(241): pocketmine\entity\Living->setHealth(double 0)
#10 src/pocketmine/plugin/MethodEventExecutor(38): TheNewHEROBRINE\Murder\MurderListener->onDamage(object pocketmine\event\entity\EntityDamageByChildEntityEvent)
#11 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(object TheNewHEROBRINE\Murder\MurderListener, object pocketmine\event\entity\EntityDamageByChildEntityEvent)
#12 src/pocketmine/event/Event(97): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByChildEntityEvent)
#13 src/pocketmine/entity/Entity(992): pocketmine\event\Event->call()
#14 src/pocketmine/entity/Living(574): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByChildEntityEvent)
#15 src/pocketmine/Player(3803): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByChildEntityEvent)
#16 src/pocketmine/entity/projectile/Projectile(318): pocketmine\Player->attack(object pocketmine\event\entity\EntityDamageByChildEntityEvent)
#17 src/pocketmine/entity/projectile/Arrow(150): pocketmine\entity\projectile\Projectile->onHitEntity(object TheNewHEROBRINE\Murder\entity\MurderPlayer, object pocketmine\math\RayTraceResult)
#18 src/pocketmine/entity/projectile/Projectile(252): pocketmine\entity\projectile\Arrow->onHitEntity(object TheNewHEROBRINE\Murder\entity\MurderPlayer, object pocketmine\math\RayTraceResult)
#19 src/pocketmine/entity/Entity(1472): pocketmine\entity\projectile\Projectile->move(double -1.208933332088, double -0.18272418071645, double -2.1806173603703)
#20 src/pocketmine/level/Level(854): pocketmine\entity\Entity->onUpdate(integer 10772)
#21 src/pocketmine/level/Level(787): pocketmine\level\Level->actuallyDoTick(integer 10772)
#22 src/pocketmine/Server(2452): pocketmine\level\Level->doTick(integer 10772)
#23 src/pocketmine/Server(2583): pocketmine\Server->checkTickUpdates(integer 10772, double 1573307152.6437)
#24 src/pocketmine/Server(2352): pocketmine\Server->tick()
#25 src/pocketmine/Server(2212): pocketmine\Server->tickProcessor()
#26 src/pocketmine/Server(1790): pocketmine\Server->start()
#27 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[60] E:\UserFiles\VASILISH\GameServers\TC73018520816563733706432\, string[68] E:\UserFiles\VASILISH\GameServers\TC73018520816563733706432\plugins\)
#28 src/pocketmine/PocketMine(299): pocketmine\server()
#29 (1): require(string[115] phar://E:/UserFiles/VASILISH/GameServers/TC73018520816563733706432/PocketMine-MP)

PocketMine-MP version: 3.10.1 [Protocol 388]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT NS301626 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) AMD64
PHP Version: 7.2.19
Zend version: 3.2.0
OS : WINNT, win

Loaded plugins:
ColorMatch 1.0.0 by for API(s) 3.0.0
PocketVote 3.0.1 by ProjectInfinity for API(s) 3.0.0
EC-TableUI 1.1.1-pre by for API(s) 3.0.0
PurePerms 1.4.2-c2a by 64FF00 & ProjectInfinity for API(s) 3.0.0
ScoreHud 5.1.1 by JackMD for API(s) 3.0.0
DevTools 1.13.5 by PocketMine Team for API(s) 3.4.0
XBedWars 1.1.3 by XenialDan for API(s) 3.9
1vs1 1.0.1 by VixikHD for API(s) 3.0.0
VanillaCoordinates 1.0.0 by Shelly7w7 for API(s) 3.0.0
PortalsPE 1.1.1 by luca28pet for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
ManyWorlds 2.2.0 by aliuly for API(s) 3.0.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
iProtector 3.1.1 by LDX for API(s) 3.0.0
FactionsPro 1.3.20 by Tethered_ for API(s) 3.0.0
MSpawns 2.2 by EvolSoft for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
MyFirstPlugin 1 by HunterV for API(s) 3.0.0
SkyWarsForPE 2.3-beta by larryTheCoder for API(s) 3.0.0+ALPHA9
Murder 0.9 by TheNewHEROBRINE for API(s) 3.0.0
MicroBattles 1.0.0 REBUILT by KaitoDoDo,LittleBigMC, A354-PH for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPAtT40aaf6XL5G4hZ9mWHxicYuoY8GS4hYEbPDOpjVNUW2rbWiS1om5hnK389/u+r1svGwYm
Ybdqr0gqAfXj6+/9Uot/NOYyjbi+uROpCmTcGHWbDR1EojFyB8NerzN0BzAScqXHaSrTxugfDb1O
YLoxgR9mrNmIhFJ8gaPH6SKLRKxZlyVcKeEzLVkivVuhoyAW02k809Op5ovp9FqnQbyY8MVodHPj
yVjpNPP07h6LMqXZTDA5Z3opGJ7HFC1uMjn7u/A0WwR3Im4yj4chHBHEbDyaTj8pkb4LQqGm08/H
12fnZ9fvp9MfeSSuRYr0TaeTk2Gv4x4Mup0Dd3+w3wMKh539fq87nSZhtghiWHORpb5InQhIFul0
qlIP9i3FB7F6P/54+fbj2Ydxvij/eR7A2likrWSZMBmzEChl7mEfODPPwhBxAtYkS56O2u3xqF0g
2s7xbFfQbD+KZfuKGHkB4J2LqxYCbAMffJm2Sxa3gcNtwLoNTG4XPEbUEB2DyjM3wQYkpTHqu6AV
Kffg158bOx1mmdWu8Yr2b3DKrmjX+bQLvNkbPaUWzpuqWhgF+Ln/CzvlmheKUIWR6SAEAQIbAx4G
vwn/LAKl3AMqdlyGyFXoNRS0L4ReSn8M/NDje+FlWqa7vQPA7ZkSd97I+FRwvdx9AB+BYFGz+Bp3
XtFPWk0HEmLdRxD7KBZ4RCr8gmmHBxs8M0sBpW0inDeCfhM5Xs+k50G+PoeO3iYdtKlNC3YPh49g
vk2l8wZt2mz7g6j0N1Exq3Z7Q3d/Aw8Ljvaak3cJxGCLmlgHet0+D+5ACXf3e4cbgMwRpTYQlP1H
EekMNhEh+NOpOcB5cxvkqAwfQWVMP3bdzqD/CC4ljIOvk+P2e4+gYw5x3iih3wseAmG+zGahYB2C
e/inHUG37z7BiUeOdjv/TIvm6Di+on91/pjlb9cnyyD0zVCpja7772Ph30JW919q8N+CWe/rFnN4
2H2mF3D7X7ebwbD/hN1wrbl3+0J0DR5zJwed3hNG9KJ47D/ClSSVCB4yjPZV8etuzz14xD+9KFLD
p5E6hmR1tesOOo8wq1wKOBa/oz94H2irPE/ZWg7LPBtKH7Q4yLmXYA58PcG06qNQWWgpOfgm9nYH
3WeQQ6T/yyk5fCJ09YfdbxRFJO9EHgcctwUJ8mEP/oGfB02Wj3da7kF3CJHlAKqX/f6gnOnCTGff
Hfb2OxCDeyYB2wokIahf2D7H/+8eDJ4ycRl/SnwObjiItViIlLmdIdBFoN2vgR4ebDpJmgWjxR9g
Hp7OwBWtT+UkADN5APyWCzYFBATVLaWog/YfBdl7DOTgYNPHmBnwl0vh3SI8wwdVB1swvywnW1DK
DM1x/ceO621RkB+nEXOze/DY7q77td2gUB7Uq5AXGDD7j4Bxh4edR8AozVNtt295nrJI2+0OB49A
qJY21qjeciVOoNJW55L7jxibLXEueBCfy8UCV9nCaL/zy58vgktoB7+8YEltGHXwNUYdbmbUygjB
bD1ku5gnpuLXLEhFXgu67uAX9tJV9V7jl9+bDfHa7PgjzY4/2l0AjhuUboL4ToZ3ArkKkILYB3l7
upHPw5jBAkY86QsUUa8Lo/Dc68FPDw2IFWcwcQ/I+op9AM74MPAPXNiHhVPd/v579t93PLXsZt+3
cW5Ac0ka3IEzY9/d8TATP+DEvj1lmG/GhwN6YAAo4SmPclDfxXAczh8+Mk9gYUG/Yxfg2X3XnA3+
MvDYPIsh6gGDt7sgBj47YtPGtNGsA7Wje0hov0sAASRPgaF11SMYe0hav2eXBXM8IBTxroG1x96w
Xne4PzTQ+nbZVOsl5BMsFis2nZ7FsDbwc1sY33siQbx3p41SDB6PY6nZUoY+i2QKer7ksYHNZmuI
Gk22gHlLCdgCILHQSyCFtVgdJ4PywOLyOz7s24fv9DJQzpucD6Xw+kZotPjAyLF/+CCzF0KjrYNh
jsDSNNI96FjwqdBZGrMPbyej0eT4xxtDHsIfuBb+7699stc+2Wuf7LVP9tone+2TvfbJXvtkr32y
1z7Za5/stU/22id77ZP9f+uTNRsLzEx4iF0Y6niMGrU1gNMMhFVeLmr0Wi64HRzPIDo1Rp1mI1A3
vrhrjOY8VKLZAJempScBZg+cVWMRYB+o88x/AHDKb8NghntabreFI5lF7UsQ+3Kl2IcJ+3ANJO6D
Ru+3XEaosOF+x2W7+RrDDNbtdA7Yxy671jz2eeqzsR9QmwDnA0+wK4jMzN1jxxen+9gBw1s2o8aw
BR70EB5/E7FPVBtMYPZGKkTl7MOHCQzQwyqIG0UDTCEvT2Qo0wuuvWWFs5XBZqPkqNvqEGyeQeqb
wvafQS48CbAD0aM5eBYxB98CqIAhAY99kWBTzKxVcq5PqwMRpz5bed50Wjs7BLNDSV9eT75cfjw/
haGVmKlAI5ZIidGBz1KLLcWgwSr6iKJbQ79hA9lZPA9iCB2NF6JnAywEzAKj6u/PIXB84kwQgU9n
FQIrg3X5wL9Okop/hoyuvSWo64fPZ6dnxxBqTyafzozTe5aYslRciTRSVSkVY3Ua+q2u43V5XVD7
/XfvOh32n+yfJLEbcwBIJ8eq8utTFC61ThQ4PHAgy2zW8mTUpr22EC/hACeuPZmK95lfYUQxVOXD
AGVZ58H/gAO4OH0pig00iH729PK35wj0VNxNpAyr8iyGNlSy1xpsGF3ht9lE8KhGUP+PE5SfP51W
MLGEXE+OP04+XT0ptQKzdgEDiP3prfC/8LRKbDG0aX+9Oq0/iTjg4SmPa1QefhuNjdPx5yDFMyBI
wfmpWEGAaJSk39MpPodq3uIFeSVlLM+RpXun3App9Ljp9jdU8XNwH9y+fzFdvENwS1BBGYs7JTHX
uIzFZwX/+wO2BxkGvz35W5sIAfo+8zgIQ34iZeoHMebDFWofmPx6yGtcLwWUAMPV8KWoVzlASOi2
sPkWQV7JVENmczWuxcJ8bCtS1MkKM493DxKhXywI5ic/P0yMIQGX0fr4qhbsysG6g4TUp04CKM4M
/nspAiw4qC8NBgATAl8VmycJuuDx+otMQ7+qcpXBKkFdm7lVCOJhkIUvFuMMNOwOxOsVnf98yZxk
SsvoeimTWiJSG64SA3580+1f81Cvr4J7EYJv/e2biKrqwNdSlNoJkEpWsLuD4gd/e44/AXeiEFSC
oFoLjgx4i5m7SDeDXm24bmEgTWcmNN9Q0pPfhLe8ugAMcQM50pO/vZSIPQSeRFDkgGxnBjdtguIG
pt/qVCtot2uggDcBJGUakjJzjcFypjJYT8K3PM/56U8vRT+Amk7Lk5+n3w9QC3Cci5OrcbtCBRD6
jtObWwWDFUqro3UVgGJsw6InQi+x1X7z5yhuHMc6uE54hGeW5FcwmU7tw3Mt/ALAreKan7IjG06q
TtD4TobXgNtLSdAeCpIrTn9GDrdarVoCMEGoLX2blxwnS643Kg4a2iw4XPehauPbXFSZ5W9Lq64h
P4m7QGYQGJ18vPFIIYLIlr+9QBlCYFDY63dBqvSVvehSirw2XmNTnUPvs1iL9PNLSd2CA6lXEXh+
eLq+XWPW+06mteSnNlxX4x755o0UiKfperIUJxITrg3S/uv4/Or98eEfpbAGG0KRwYzQeto0zTWk
ipjye0klRZ3W4Yanqb9FeClJPfFK89neJvBS+ZZrHday8drwVh7OPo7ffjo7n9QJ/SsPtDyFf5vn
AW58GywuTprsuDfoO1fvXyyylLCB1gqa9aenacf2G97PEqDwG+Vw/qEd7PgPvPLlOKbj6gTJkTtw
WwdQhx0eQEXdpckEEuwj9zB/jPi9Yy5hqCO3Q0MppE2tjWWGeOfXTKTrIyopHQe4KR3F70Q+EIlI
pmsnDKJAH/U6w+4FeTXCppWkMoG0IkDJNXauiid2IuN5sGB4NW+aTuOdL8Jnl55mvQ5zu6PB/mjQ
Yz9eTFi34x7iAksdyv4or1thOJLaPzqXK8rkKuu2uFCZK4nEQRnjbT8nAls7kvM5DtHbFnMU5b7l
GF6DPDodvzv+dD7BUaywaWeHkKlxlU7EuOQkJi8A7TxyXBzGW2dZ7Am72uHeMhDmdqECtuKS1RKU
AJiqdI7VhjAqQyg6O2KkyJUCxP2j7+kfOC8M5cqZh8FiWYAzqEENGUHhZXebsUjO8oG5TAHLgkq7
FdTOx/5P/pzcJXa9H8zngZdBPnxEhJpGPF53UELrIF6oo5KZSgifHqsqhc93gVg5PpDOgUdHBzh0
P5P3qHpLuyTk8SLjC3Ek4gU+Yxe7ePvQWkchqhtDD8M80rQM0MAOOSocA7JYzZRIBfFlqhIsx5Rx
ug8oGNR1Ci8G6vy64EywIPbCzDfXXrdU3UC7llF+fXYTquJz0WQS0zuFQNksFfyWrWWWWmgsmDNg
eTAP6AzgNt43hYqMQINXLQC2fTHnwHHFVjL+i2Y8SQRPGfI0ApLxOsQascQ7iIb61VLELEsWKfcB
QAtBGuswAEf4wHYmy1SAAsIgYJOzm+HlVmKftSUVwHMoPbywRww2m0/wpaKhp74VJJCnHiJurYLb
IBF+wFsyXbTxqY33Sm7k/Obs+vJmv3fodG9wH7G0ADVi0wbKvWEO+7KkRBkvOSvwxQwotu/BQGwp
j1XItbkDbXlL+AIu8JvQJGIogvC1yZLHfkhCjwi0Uf/yWHoXRDNqmWlforGYW9eIkn0544VSCT9H
7hhNj6Ed4w1S+zKF3QWc/S8aMi0ik3bs3IhhpDGboQhdMY4arCTgZc8yAuQWGMsUqCfEJVAQohMK
X1iJF44M18opB9CbAXLVI8bkQnJYQD9Dy2agzKAriPJszayG0Qbrcor5KlN2vgTAenCoa8Z9n6V0
l0AZdPHNLaDFFWSWdDcdtHEmkDcgBvFrxkMUEF0pZ+ai7K49FkLAHoE3Z4K7E+jBHZAwvkEdwbw5
/UMWzYD/YHLHah17E65uwSbSWzCyllnxCe/Co/bm5OK6ZSrBG4OqwHrVZOTxmXVcoNBNYEgEHFSY
XRCDIELjWJTFYF24xEK/JmUCusAEU3kPjlULYAWQRYYQF+ghh3OUzuZoybgILbbJAv0X4KFOaZ8v
MG6Qhm7sZrtABUiedQ1viBLHUjsiWFvGQVGApVkco1x99MEyIVlQ9a9aDCp2+zuLMFYwL+Vq2ay6
J6ulyJU0zRJtRg3TkDl4izonjYQMuge8Ars0JsjvZOAD5g+jgLqC2ieB26BmrarKwWrHrCr1l6Iu
5R/Wa/0YyhmoEmZmzEwwSkzQA0ZiwelSd4tdG5Z3iMmBQvi51wOUVwGJgNSLYeS0KY4dUkToPABE
wXXTZSeEMwd/mZ9pVB7ElpHBLiRITKJzQP2gkxaEqMmaRqyTE8N2KGZpcL7c/zcgAzPeJ4jAbOFP
EqG0TAgP68ALvCw8xcCtmE9dSqzw3Bw1t9Ptl9iRe/hCtmKRVH95CTTJWsznMuh7vCzFzxvABZir
nvQJgcHbGCoG+WK1uPcgH1IlWdapXU7GIzZ5f3bNzs8uzibg3q/Oz8bX7Gr8kUHN8NfxxyaDRWxy
CavG7Mv7y/Mxu/p4eTK+vm5t+YYaV7qD/ZIpVyINJOUz6KoVkklXg3KeFO7YBSlARPKN46E1DrhK
kTtimwHIGAgGNw4KhoQ/pn9G7yDbDSk5QA9llhnoBgq459LdV22f7VxitMFkiTa1tjegdtgiDoSY
CA9zKsNmxNpI2ewtSAGFE4kqSYaixNCs9h5By3KgV3JgwdMZGI3jyTA0yb9xUQ9ymqwQUbK7mN0F
Tj7iMd0jq2EDWW4GWrnXzIPHllpavTTBeD4HWIbmqLTMFrs0ocGYAOQ0Mgv9ApcAos0qZiX+xuJZ
QugDrfudTkku23lHnmQropIiGRgFdfNURnloNrvtCqeqqxuiBoqsRLf15AH12lSU6zwBR+GlcBxq
pdVtP4sSk/zlCbGdcXAml9sprrI7iAJCNqcDniAzAC/AH2A0RHmIk3DEHSicUplAj6GXIL1Fnryj
S8PTSrSauUBNVmHzc4MeLf0at7AW9ZZZfKty9E94gqNBlEUQlCEepyyvsVCmzNSiBpGSvWg+lqNk
QNvqBgVMYpGiAx2sKzII0v2K6E6lmdxUcMyp0CeaE8zi3KQMNLtwgzxKOBwPCmdREHgK+FCKA8kn
chFQNHmJAZRwLPiY2WPILEmEbZavhqj8cFxcSZeBiyFWVxbu10E9pZP4Xyw0iq9Scyn6GA2T1Ble
bKKqgTCHnAs0ykYjcnumsrSzJgTNRJGu2li4UxVZPoduN13rJX3O6bgVaRpJ0tGOztEpQgX69TIZ
pjIes1Df8ACrLyoZcDcMWsxa7D0kk6BaR+Ybu5OrT03YC1jMwORWgQ+GQAmG9a3FAQ4dMGLDInsv
M3tFLKosbrFjH5zYkofzNlTspuDwBSi1PQyOZdhvQ32rGGclRFag1cqa8T36PExTedg0LhUPt5fy
Wgz8kiA/hwn5p6v4Kk/nywIcKxbchJcxCGiWxIljBzbLqAtrpSr4TRQyx9Q/F7XCmGkTMSgNjA5V
InT/sGs27bXoKiDuCXm6oA3c9gKsvpgj5ylfIIEgNSzuk5DyHyyZI/y8F7wDT1GSJ2GATSpqWuB1
TqE0u5h8IlQVEIWUzzLNsE1SflBJ55kKplV4p0hnDm4bEb65Qfhili1yc5A2cjNM7VJyFjaVwroM
Qx/eZGwVswq5ZcqUZdIK4gDRca2E8zW5u/jC0xgzh8pu7M3YXAEhWSDghyGPQZGWKyMOth6BPDSq
E9RU+Mfp0I3S361DlwqQ87TDHAiSjp1gbpuqfrUIh/DwhrlY/Nl8F+t+4kRe8yvTwhF5L8D0Q4x5
uNVKXrE2+HSdgbdoL7zcogAlLJsKHaOuHfn7Ud6wkVJRZyGvFkXeGKCo4HPNmeJ3RQDCdl3evsTJ
CjkcmAH+U3CdsxroM9do85qEqluwNUr+VAKJLyWDsfTCIGG0F5TtApjscTQq/HDAdg0weFqOmrZm
PmeO3CgO807jRmtL5D0NZv7OoGnv0WJrGJmyfRYPnIS2vtRucsymEUuAr3dBaKuKmsF7oPcQ5ixI
ckaUWQLd6Hw0OqBux2aAGH5NgmkYiP1QnLFZZcnZ2kSRxncKR29SD7zcXDly1wXP+8BZTdaFCfeh
CaG91p6NBEpUcbHKhh8MUKPN9ruZgFhozkShGtZRg7PsfPp5fEZ3YEuTcMXXysC3kDa01MRhG1lK
v2DZa+vBGOURbmY1zXxVrZ/8YMfWdiyOI5mhZ52blME6WlRVSyXyCJE1/ShQfXywmQ7b+UiJT2U7
aVUsTOdjJgy4mZijY6ReO6Upy9zKjGFRD34rhzJ8wONKPkCcYHwT5cR8HgFnFiLZxLbzCLo8BVg+
dRbJ6AHpYrtVAYNVz7gfbBE5mflspBrAPMyRjFCx8VnzdKd04CyUqHIYJZC7xm2CtkJAjZglkuWN
tTwlo011FrAdB5R4hy2g8lZ1VpUdvJJbrW12Wbe64gHV5xDRjK+fYRcqycLC9u0TpiW0yMaug/xU
MiInyT0qmir6yBGrlklkwKZ/OcqNFluu1Dgw4yaxsVIMzNsNth0z0CIcbI1vjhW+bmMcglkQz2VV
TuDjHNONL9cuJQqMEGolUQQBUBbIxzJeR1j0YoTBjranKlRgPW8XsHIBUUPRgy8WqVjYnmrRu8Za
AP80we0WqYQnGPvl6SV+OmLjps1d0L2shCmoOP3FBzxSEfoVOmiwVXkzBLlSTRZGe63MtrkMwjYr
RpUYbkNwtSygcVljJNRbMWpRpcnZBH+XLHmT4XUCyrN0mXJDNJyLFIosB71WjIEdlxUJgmmZ8lrT
1L7zriQOGZQZkJKR48udi4VnVMEsyM/Ylrwhd1P0kN1U4qdNFhA2bsozX5Q0ulo8l5Iwuyt/EdCq
HGOnNs/JWftEUmLdvhG5MZtKcy1/XaIDnTM3b6Mt7Sj5GCx2bc1kXQy+s4AC1ad6IZgXkKAGBXpM
fog+q5bYEUDrWqupBw8DiJ05z8b3PErC4hEzPMDVCnCUS9JOglZjy3PEfqY0C6Jmk3qgv+SwzZXM
Mp2pvmAkmrA4SPHdHDWV8rewlDI/FP8o+6LgrKhGoiYEyCwAlG0OUyPDnkxo2N8Zvs7F4GKDYXnq
iL07P56Muj8Mm4PDe7fZu+81uz+4P/iQbBgPvatTAQ/gmY8OOsaZm6f+YK9MV83rsVo3x3gDjFPA
eNuEpYSRuqggS2/NzFd6WZq79bxeTYu3XuSeAA6EPY8yf5VzzsnfyoGG2NJl5x35JTqLNtSgZJSB
2D8aVBlxKEluVTrGMrH1DPhJZet97xbLQUVlLTBmFkAZtjadIlqHFAMyUIaaSGRNyhBKJ0Cak1Zc
fKPZoL80pOjmGH3ClYrql2AzD7//rY7gq1H8qKw2JqMbX2pwnrVR+0eoyoEsDavP6Emqz/Mg1KIG
eBHVvktbQtQxF3jgIQDru6vO/l3Z6z37NB/NzEve6hJlP4irjiVeneSPYm47T7WdFCNUfQiynag6
cn11Xn2M1urXkL6ks7+xAX7+0MVXVczBqyuDTr8zhF+/O8OG6eDQ9Tn3u11fdA4G3X73cCDcmd8Z
9kCNxHzuumJ/MDxk3wFsLW9FDBlGjV1rThcbunAKftX3W5CY+/kD82g+MCxWw+N9VBeIRHK6nU7P
dbs4APYfK1Vbs7Elsd1h+7mgi99ENhtXS1IQRKRbu3pxQ2kVfeZqvnU0olzMgpin68qHdQQRLz6T
4qTrREva0KPZhb/F56AmGnjWolcdSgWoH+r5IjMKYA7//ff/Ax8PhvQ=
===END CRASH DUMP===

**Comment by TheNewHEROBRINEX** [comment]
PocketMine-MP 3.10 is unsupported by the plugin.

**Comment by ElectroGamesYT** [comment]
Come on dude, fix it ;/
