### ISSUE TITLE
Add support genisysPRO

### ISSUE THREAD

**Issue by oGalatico** [TheNewHEROBRINEX/Murder#5]
Pls :)

**Comment by TheNewHEROBRINEX** [comment]
Has GenisysPro the API 3.0.0-ALPHA7?

**Comment by TheNewHEROBRINEX** [comment]
As I can see here
https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/PocketMine.php#L80
No.
So if I make the plugin compatible with GenisysPro it won't be compatible with PocketMine-MP.

**Comment by Kenner-G** [comment]
@oGalatico 

---

This is warning: on the TODO list #1 you asked to make it work with GenisysPro, the author already said no. If you continue, the author will mute you from further discussions on this plugin.
