### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Kenner-G** [TheNewHEROBRINEX/Murder#9]
Fatal error: Declaration of TheNewHEROBRINE\Murder\entities\projectiles\MurderKnifeProjectile::onUpdate($currentTick): bool must be compatible with pocketmine\entity\Entity::onUpdate(int $currentTick): bool in /root/Xygo/Murder-Mystery/plugins/Murder/src/TheNewHEROBRINE/Murder/entities/projectiles/MurderKnifeProjectile.php on line 9

**Comment by TheNewHEROBRINEX** [comment]
This is fixed in the dev branch

**Comment by Kenner-G** [comment]
Okay, thanks!

**Comment by Kenner-G** [comment]
How do we download the dev branch?

**Comment by TheNewHEROBRINEX** [comment]
how do you download the master branch?

**Comment by TheNewHEROBRINEX** [comment]
Branch dev merged

**Comment by Kenner-G** [comment]
Thanks!
